Repository petrYar/Wardrobe, pull requests merged in 2020-05, with the labels that each got.

#17 Fixed bug
  Wardobe/.vs/Wardobe/v16/.suo
  Wardobe/WardobeClient/LoginWindow.xaml.cs
  Wardobe/WardobeClient/obj/Debug/DesignTimeResolveAssemblyReferencesInput.cache
  Wardobe/WardobeClient/obj/Debug/LoginWindow.g.i.cs
  Wardobe/WardobeClient/obj/Debug/WardobeClient.csprojAssemblyReference.cache
  Wardobe/WardobeClient/obj/Debug/WardobeClient_MarkupCompile.i.cache
  Wardobe/WardobeHost/bin/Debug/WardobeHost.exe
  Wardobe/WardobeHost/bin/Debug/WardobeHost.pdb
  Wardobe/WardobeHost/bin/Debug/WardobeLibrary.dll
  Wardobe/WardobeHost/bin/Debug/WardobeLibrary.pdb
  Wardobe/WardobeHost/obj/Debug/WardobeHost.csproj.FileListAbsolute.txt
  Wardobe/WardobeHost/obj/Debug/WardobeHost.csprojAssemblyReference.cache
  Wardobe/WardobeHost/obj/Debug/WardobeHost.exe
  Wardobe/WardobeHost/obj/Debug/WardobeHost.pdb
  Wardobe/WardobeLibrary/bin/Debug/WardobeLibrary.dll
  Wardobe/WardobeLibrary/bin/Debug/WardobeLibrary.pdb
  Wardobe/WardobeLibrary/obj/Debug/WardobeLibrary.csproj.FileListAbsolute.txt
  Wardobe/WardobeLibrary/obj/Debug/WardobeLibrary.csprojAssemblyReference.cache
  Wardobe/WardobeLibrary/obj/Debug/WardobeLibrary.dll
  Wardobe/WardobeLibrary/obj/Debug/WardobeLibrary.pdb
Labels: bug

#20 connected LoginWindow with MainWindow
  Wardobe/.vs/Wardobe/v16/.suo
  Wardobe/.vs/Wardobe/v16/Server/sqlite3/storage.ide
  Wardobe/WardobeClient/LoginWindow.xaml
  Wardobe/WardobeClient/LoginWindow.xaml.cs
  Wardobe/WardobeClient/RegisterWindow.xaml
  Wardobe/WardobeClient/RegisterWindow.xaml.cs
  Wardobe/WardobeClient/obj/Debug/LoginWindow.g.i.cs
  Wardobe/WardobeClient/obj/Debug/RegisterWindow.g.i.cs
  Wardobe/WardobeClient/obj/Debug/WardobeClient.csprojAssemblyReference.cache
Labels: bug

#19 Feature/001
  Wardrobe/Wardobe.sln
  Wardrobe/WardobeClient/App.config
  Wardrobe/WardobeClient/App.xaml
  Wardrobe/WardobeClient/App.xaml.cs
  Wardrobe/WardobeClient/Connected Services/Proxy/AccountService.wsdl
  Wardrobe/WardobeClient/Connected Services/Proxy/Design_Time_Addresses.disco
  Wardrobe/WardobeClient/Connected Services/Proxy/Design_Time_Addresses.xsd
  Wardrobe/WardobeClient/Connected Services/Proxy/Design_Time_Addresses1.xsd
  Wardrobe/WardobeClient/Connected Services/Proxy/Design_Time_Addresses2.xsd
  Wardrobe/WardobeClient/Connected Services/Proxy/Reference.cs
  Wardrobe/WardobeClient/Connected Services/Proxy/Reference.svcmap
  Wardrobe/WardobeClient/Connected Services/Proxy/WardobeClient.Proxy.Account.datasource
  Wardrobe/WardobeClient/Connected Services/Proxy/configuration.svcinfo
  Wardrobe/WardobeClient/Connected Services/Proxy/configuration91.svcinfo
  Wardrobe/WardobeClient/LoginWindow.xaml
  Wardrobe/WardobeClient/LoginWindow.xaml.cs
  Wardrobe/WardobeClient/MainWindow.xaml
  Wardrobe/WardobeClient/MainWindow.xaml.cs
  Wardrobe/WardobeClient/Properties/AssemblyInfo.cs
  Wardrobe/WardobeClient/Properties/Resources.Designer.cs
  Wardrobe/WardobeClient/Properties/Resources.resx
  Wardrobe/WardobeClient/Properties/Settings.Designer.cs
  Wardrobe/WardobeClient/Properties/Settings.settings
  Wardrobe/WardobeClient/RegisterWindow.xaml
  Wardrobe/WardobeClient/RegisterWindow.xaml.cs
  Wardrobe/WardobeClient/WardobeClient.csproj
  Wardrobe/WardobeClient/packages.config
  Wardrobe/WardobeHost/App.config
  Wardrobe/WardobeHost/Program.cs
  Wardrobe/WardobeHost/Properties/AssemblyInfo.cs
  Wardrobe/WardobeHost/WardobeHost.csproj
  Wardrobe/WardobeLibrary/App.config
  Wardrobe/WardobeLibrary/Migrations/202005041712101_created database.Designer.cs
  Wardrobe/WardobeLibrary/Migrations/202005041712101_created database.cs
  Wardrobe/WardobeLibrary/Migrations/202005041712101_created database.resx
  Wardrobe/WardobeLibrary/Migrations/Configuration.cs
  Wardrobe/WardobeLibrary/Models/AccountDB.cs
  Wardrobe/WardobeLibrary/Models/CategoriesDB.cs
  Wardrobe/WardobeLibrary/Models/ClothesDB.cs
  Wardrobe/WardobeLibrary/Models/EFContext.cs
  Wardrobe/WardobeLibrary/Properties/AssemblyInfo.cs
  Wardrobe/WardobeLibrary/WCFClasses/Classes/Account.cs
  Wardrobe/WardobeLibrary/WCFClasses/Classes/Categories.cs
  Wardrobe/WardobeLibrary/WCFClasses/Classes/Clothes.cs
  Wardrobe/WardobeLibrary/WCFClasses/Services/AccountService.cs
  Wardrobe/WardobeLibrary/WCFClasses/Services/IAccountService.cs
  Wardrobe/WardobeLibrary/WCFClasses/Services/IWardobeService.cs
  Wardrobe/WardobeLibrary/WCFClasses/Services/WardobeService.cs
  Wardrobe/WardobeLibrary/WardobeLibrary.csproj
  Wardrobe/WardobeLibrary/packages.config
Labels: help wanted, invalid

#23 Feature/011,012 #2
  Wardrobe/WardobeLibrary/WCFClasses/Services/WardobeService.cs
Labels: enhancement, help wanted

#24 Feature/007
  Wardrobe/WardobeClient/LoginWindow.xaml
  Wardrobe/WardobeClient/LoginWindow.xaml.cs
  Wardrobe/WardobeClient/RegisterWindow.xaml
  Wardrobe/WardobeClient/RegisterWindow.xaml.cs
Labels: bug

#32 Feature/007
  Wardrobe/WardobeClient/Connected Services/Proxy/Design_Time_Addresses.xsd
  Wardrobe/WardobeClient/Connected Services/Proxy/Design_Time_Addresses1.xsd
  Wardrobe/WardobeClient/Connected Services/Proxy/Reference.cs
  Wardrobe/WardobeClient/LoginWindow.xaml
  Wardrobe/WardobeClient/LoginWindow.xaml.cs
  Wardrobe/WardobeClient/RegisterWindow.xaml.cs
  Wardrobe/WardobeHost/App.config
  Wardrobe/WardobeHost/WardobeHost.csproj
  Wardrobe/WardobeHost/packages.config
  Wardrobe/WardobeLibrary/Migrations/202005121801126_edited classe.Designer.cs
  Wardrobe/WardobeLibrary/Migrations/202005121801126_edited classe.cs
  Wardrobe/WardobeLibrary/Migrations/202005121801126_edited classe.resx
  Wardrobe/WardobeLibrary/Migrations/202005131649421_edited tables.Designer.cs
  Wardrobe/WardobeLibrary/Migrations/202005131649421_edited tables.cs
  Wardrobe/WardobeLibrary/Migrations/202005131649421_edited tables.resx
  Wardrobe/WardobeLibrary/Migrations/202005141256218_asf.Designer.cs
  Wardrobe/WardobeLibrary/Migrations/202005141256218_asf.cs
  Wardrobe/WardobeLibrary/Migrations/202005141256218_asf.resx
  Wardrobe/WardobeLibrary/Migrations/202005141331170_removed Required.Designer.cs
  Wardrobe/WardobeLibrary/Migrations/202005141331170_removed Required.cs
  Wardrobe/WardobeLibrary/Migrations/202005141331170_removed Required.resx
  Wardrobe/WardobeLibrary/Models/AccountDB.cs
  Wardrobe/WardobeLibrary/Models/CategoriesDB.cs
  Wardrobe/WardobeLibrary/Models/ClothesDB.cs
  Wardrobe/WardobeLibrary/Models/EFContext.cs
  Wardrobe/WardobeLibrary/WCFClasses/Classes/Account.cs
  Wardrobe/WardobeLibrary/WCFClasses/Services/AccountService.cs
  Wardrobe/WardobeLibrary/WCFClasses/Services/IAccountContract.cs
  Wardrobe/WardobeLibrary/WCFClasses/Services/IWardobeContract.cs
  Wardrobe/WardobeLibrary/WardobeLibrary.csproj
Labels: bug
